baseURL = "https://dongxuwang.github.io/"
copyright = "© Dongxu Wang"
languageCode = "en-us"
theme = "ink"
title = "Dongxu Wang"
# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
paginate = 10 # articles per page

googleAnalytics = ""

[params]
avatar = "https://avatars.githubusercontent.com/u/4261431"
mode = "light"
featherIconsCDN = true
subtitle = "The road to develop"
excludedTypes = ["page", "pages"]

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/dongxuwang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
